// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#include "Protocol.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr SC_REMOVE_OBJECT::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_REMOVE_OBJECT::SC_REMOVE_OBJECT(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SC_REMOVE_OBJECTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_REMOVE_OBJECTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_REMOVE_OBJECTDefaultTypeInternal() {}
  union {
    SC_REMOVE_OBJECT _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_REMOVE_OBJECTDefaultTypeInternal _SC_REMOVE_OBJECT_default_instance_;

inline constexpr POSITION::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR POSITION::POSITION(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct POSITIONDefaultTypeInternal {
  PROTOBUF_CONSTEXPR POSITIONDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~POSITIONDefaultTypeInternal() {}
  union {
    POSITION _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 POSITIONDefaultTypeInternal _POSITION_default_instance_;

inline constexpr CS_LOGOUT::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CS_LOGOUT::CS_LOGOUT(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CS_LOGOUTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_LOGOUTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_LOGOUTDefaultTypeInternal() {}
  union {
    CS_LOGOUT _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_LOGOUTDefaultTypeInternal _CS_LOGOUT_default_instance_;

inline constexpr CS_LOGIN::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        time_test_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CS_LOGIN::CS_LOGIN(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CS_LOGINDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_LOGINDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_LOGINDefaultTypeInternal() {}
  union {
    CS_LOGIN _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_LOGINDefaultTypeInternal _CS_LOGIN_default_instance_;

inline constexpr CHARDATA::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : power_{0},
        defensive_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CHARDATA::CHARDATA(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CHARDATADefaultTypeInternal {
  PROTOBUF_CONSTEXPR CHARDATADefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CHARDATADefaultTypeInternal() {}
  union {
    CHARDATA _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CHARDATADefaultTypeInternal _CHARDATA_default_instance_;

inline constexpr SC_POS::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pos_{nullptr},
        id_{::int64_t{0}},
        move_time_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR SC_POS::SC_POS(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SC_POSDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_POSDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_POSDefaultTypeInternal() {}
  union {
    SC_POS _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_POSDefaultTypeInternal _SC_POS_default_instance_;

inline constexpr SC_CLIENTCONNECT::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        chardata_{nullptr},
        startpos_{nullptr},
        id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR SC_CLIENTCONNECT::SC_CLIENTCONNECT(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SC_CLIENTCONNECTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_CLIENTCONNECTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_CLIENTCONNECTDefaultTypeInternal() {}
  union {
    SC_CLIENTCONNECT _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_CLIENTCONNECTDefaultTypeInternal _SC_CLIENTCONNECT_default_instance_;

inline constexpr CS_MOVE::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pos_{nullptr},
        id_{::int64_t{0}},
        move_time_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR CS_MOVE::CS_MOVE(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CS_MOVEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_MOVEDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_MOVEDefaultTypeInternal() {}
  union {
    CS_MOVE _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_MOVEDefaultTypeInternal _CS_MOVE_default_instance_;
static ::_pb::Metadata file_level_metadata_Protocol_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Protocol_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Protocol_2eproto = nullptr;
const ::uint32_t TableStruct_Protocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::POSITION, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::POSITION, _impl_.x_),
    PROTOBUF_FIELD_OFFSET(::POSITION, _impl_.y_),
    PROTOBUF_FIELD_OFFSET(::POSITION, _impl_.z_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CHARDATA, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CHARDATA, _impl_.power_),
    PROTOBUF_FIELD_OFFSET(::CHARDATA, _impl_.defensive_),
    PROTOBUF_FIELD_OFFSET(::SC_CLIENTCONNECT, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SC_CLIENTCONNECT, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SC_CLIENTCONNECT, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::SC_CLIENTCONNECT, _impl_.chardata_),
    PROTOBUF_FIELD_OFFSET(::SC_CLIENTCONNECT, _impl_.startpos_),
    ~0u,
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SC_POS, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_.pos_),
    PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_.move_time_),
    ~0u,
    0,
    ~0u,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::SC_REMOVE_OBJECT, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SC_REMOVE_OBJECT, _impl_.id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CS_LOGIN, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CS_LOGIN, _impl_.user_name_),
    PROTOBUF_FIELD_OFFSET(::CS_LOGIN, _impl_.time_test_),
    PROTOBUF_FIELD_OFFSET(::CS_MOVE, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CS_MOVE, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CS_MOVE, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::CS_MOVE, _impl_.pos_),
    PROTOBUF_FIELD_OFFSET(::CS_MOVE, _impl_.move_time_),
    ~0u,
    0,
    ~0u,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CS_LOGOUT, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CS_LOGOUT, _impl_.id_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::POSITION)},
        {11, -1, -1, sizeof(::CHARDATA)},
        {21, 32, -1, sizeof(::SC_CLIENTCONNECT)},
        {35, 46, -1, sizeof(::SC_POS)},
        {49, -1, -1, sizeof(::SC_REMOVE_OBJECT)},
        {58, -1, -1, sizeof(::CS_LOGIN)},
        {68, 79, -1, sizeof(::CS_MOVE)},
        {82, -1, -1, sizeof(::CS_LOGOUT)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_POSITION_default_instance_._instance,
    &::_CHARDATA_default_instance_._instance,
    &::_SC_CLIENTCONNECT_default_instance_._instance,
    &::_SC_POS_default_instance_._instance,
    &::_SC_REMOVE_OBJECT_default_instance_._instance,
    &::_CS_LOGIN_default_instance_._instance,
    &::_CS_MOVE_default_instance_._instance,
    &::_CS_LOGOUT_default_instance_._instance,
};
const char descriptor_table_protodef_Protocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016Protocol.proto\"+\n\010POSITION\022\t\n\001x\030\001 \001(\002\022"
    "\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\",\n\010CHARDATA\022\r\n\005pow"
    "er\030\001 \001(\002\022\021\n\tdefensive\030\002 \001(\002\"X\n\020SC_CLIENT"
    "CONNECT\022\n\n\002id\030\001 \001(\003\022\033\n\010charData\030\002 \001(\0132\t."
    "CHARDATA\022\033\n\010startPos\030\003 \001(\0132\t.POSITION\"\?\n"
    "\006SC_POS\022\n\n\002id\030\001 \001(\003\022\026\n\003pos\030\002 \001(\0132\t.POSIT"
    "ION\022\021\n\tmove_time\030\003 \001(\003\"\036\n\020SC_REMOVE_OBJE"
    "CT\022\n\n\002id\030\001 \001(\003\"0\n\010CS_LOGIN\022\021\n\tuser_name\030"
    "\001 \001(\014\022\021\n\ttime_test\030\002 \001(\003\"@\n\007CS_MOVE\022\n\n\002i"
    "d\030\001 \001(\003\022\026\n\003pos\030\002 \001(\0132\t.POSITION\022\021\n\tmove_"
    "time\030\003 \001(\003\"\027\n\tCS_LOGOUT\022\n\n\002id\030\001 \001(\003*2\n\tD"
    "irection\022\006\n\002UP\020\000\022\010\n\004DOWN\020\001\022\010\n\004LEFT\020\002\022\t\n\005"
    "RIGHT\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_Protocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false,
    false,
    495,
    descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_Protocol_2eproto::offsets,
    file_level_metadata_Protocol_2eproto,
    file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Protocol_2eproto_getter() {
  return &descriptor_table_Protocol_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Protocol_2eproto(&descriptor_table_Protocol_2eproto);
const ::google::protobuf::EnumDescriptor* Direction_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Protocol_2eproto);
  return file_level_enum_descriptors_Protocol_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Direction_internal_data_[] = {
    262144u, 0u, };
bool Direction_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class POSITION::_Internal {
 public:
};

POSITION::POSITION(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:POSITION)
}
POSITION::POSITION(
    ::google::protobuf::Arena* arena, const POSITION& from)
    : POSITION(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE POSITION::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void POSITION::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
POSITION::~POSITION() {
  // @@protoc_insertion_point(destructor:POSITION)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void POSITION::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void POSITION::Clear() {
// @@protoc_insertion_point(message_clear_start:POSITION)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* POSITION::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> POSITION::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_POSITION_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(POSITION, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(POSITION, _impl_.y_)}},
    // float z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(POSITION, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(POSITION, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(POSITION, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float z = 3;
    {PROTOBUF_FIELD_OFFSET(POSITION, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* POSITION::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:POSITION)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float x = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_y(), target);
  }

  // float z = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:POSITION)
  return target;
}

::size_t POSITION::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:POSITION)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 5;
  }

  // float y = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 5;
  }

  // float z = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData POSITION::_class_data_ = {
    POSITION::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* POSITION::GetClassData() const {
  return &_class_data_;
}

void POSITION::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<POSITION*>(&to_msg);
  auto& from = static_cast<const POSITION&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:POSITION)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void POSITION::CopyFrom(const POSITION& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:POSITION)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool POSITION::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* POSITION::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void POSITION::InternalSwap(POSITION* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(POSITION, _impl_.z_)
      + sizeof(POSITION::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(POSITION, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata POSITION::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[0]);
}
// ===================================================================

class CHARDATA::_Internal {
 public:
};

CHARDATA::CHARDATA(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CHARDATA)
}
CHARDATA::CHARDATA(
    ::google::protobuf::Arena* arena, const CHARDATA& from)
    : CHARDATA(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CHARDATA::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CHARDATA::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, power_),
           0,
           offsetof(Impl_, defensive_) -
               offsetof(Impl_, power_) +
               sizeof(Impl_::defensive_));
}
CHARDATA::~CHARDATA() {
  // @@protoc_insertion_point(destructor:CHARDATA)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CHARDATA::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CHARDATA::Clear() {
// @@protoc_insertion_point(message_clear_start:CHARDATA)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.power_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.defensive_) -
      reinterpret_cast<char*>(&_impl_.power_)) + sizeof(_impl_.defensive_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CHARDATA::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> CHARDATA::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CHARDATA_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // float defensive = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(CHARDATA, _impl_.defensive_)}},
    // float power = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(CHARDATA, _impl_.power_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float power = 1;
    {PROTOBUF_FIELD_OFFSET(CHARDATA, _impl_.power_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float defensive = 2;
    {PROTOBUF_FIELD_OFFSET(CHARDATA, _impl_.defensive_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CHARDATA::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CHARDATA)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float power = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_power = this->_internal_power();
  ::uint32_t raw_power;
  memcpy(&raw_power, &tmp_power, sizeof(tmp_power));
  if (raw_power != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_power(), target);
  }

  // float defensive = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_defensive = this->_internal_defensive();
  ::uint32_t raw_defensive;
  memcpy(&raw_defensive, &tmp_defensive, sizeof(tmp_defensive));
  if (raw_defensive != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_defensive(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CHARDATA)
  return target;
}

::size_t CHARDATA::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CHARDATA)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float power = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_power = this->_internal_power();
  ::uint32_t raw_power;
  memcpy(&raw_power, &tmp_power, sizeof(tmp_power));
  if (raw_power != 0) {
    total_size += 5;
  }

  // float defensive = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_defensive = this->_internal_defensive();
  ::uint32_t raw_defensive;
  memcpy(&raw_defensive, &tmp_defensive, sizeof(tmp_defensive));
  if (raw_defensive != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CHARDATA::_class_data_ = {
    CHARDATA::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CHARDATA::GetClassData() const {
  return &_class_data_;
}

void CHARDATA::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CHARDATA*>(&to_msg);
  auto& from = static_cast<const CHARDATA&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CHARDATA)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_power = from._internal_power();
  ::uint32_t raw_power;
  memcpy(&raw_power, &tmp_power, sizeof(tmp_power));
  if (raw_power != 0) {
    _this->_internal_set_power(from._internal_power());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_defensive = from._internal_defensive();
  ::uint32_t raw_defensive;
  memcpy(&raw_defensive, &tmp_defensive, sizeof(tmp_defensive));
  if (raw_defensive != 0) {
    _this->_internal_set_defensive(from._internal_defensive());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CHARDATA::CopyFrom(const CHARDATA& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CHARDATA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CHARDATA::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CHARDATA::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CHARDATA::InternalSwap(CHARDATA* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CHARDATA, _impl_.defensive_)
      + sizeof(CHARDATA::_impl_.defensive_)
      - PROTOBUF_FIELD_OFFSET(CHARDATA, _impl_.power_)>(
          reinterpret_cast<char*>(&_impl_.power_),
          reinterpret_cast<char*>(&other->_impl_.power_));
}

::google::protobuf::Metadata CHARDATA::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[1]);
}
// ===================================================================

class SC_CLIENTCONNECT::_Internal {
 public:
  using HasBits = decltype(std::declval<SC_CLIENTCONNECT>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_._has_bits_);
  static const ::CHARDATA& chardata(const SC_CLIENTCONNECT* msg);
  static void set_has_chardata(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::POSITION& startpos(const SC_CLIENTCONNECT* msg);
  static void set_has_startpos(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::CHARDATA& SC_CLIENTCONNECT::_Internal::chardata(const SC_CLIENTCONNECT* msg) {
  return *msg->_impl_.chardata_;
}
const ::POSITION& SC_CLIENTCONNECT::_Internal::startpos(const SC_CLIENTCONNECT* msg) {
  return *msg->_impl_.startpos_;
}
SC_CLIENTCONNECT::SC_CLIENTCONNECT(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SC_CLIENTCONNECT)
}
inline PROTOBUF_NDEBUG_INLINE SC_CLIENTCONNECT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SC_CLIENTCONNECT::SC_CLIENTCONNECT(
    ::google::protobuf::Arena* arena,
    const SC_CLIENTCONNECT& from)
    : ::google::protobuf::Message(arena) {
  SC_CLIENTCONNECT* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.chardata_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::CHARDATA>(arena, *from._impl_.chardata_)
                : nullptr;
  _impl_.startpos_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::POSITION>(arena, *from._impl_.startpos_)
                : nullptr;
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:SC_CLIENTCONNECT)
}
inline PROTOBUF_NDEBUG_INLINE SC_CLIENTCONNECT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_CLIENTCONNECT::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chardata_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, chardata_) +
               sizeof(Impl_::id_));
}
SC_CLIENTCONNECT::~SC_CLIENTCONNECT() {
  // @@protoc_insertion_point(destructor:SC_CLIENTCONNECT)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SC_CLIENTCONNECT::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.chardata_;
  delete _impl_.startpos_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SC_CLIENTCONNECT::Clear() {
// @@protoc_insertion_point(message_clear_start:SC_CLIENTCONNECT)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.chardata_ != nullptr);
      _impl_.chardata_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.startpos_ != nullptr);
      _impl_.startpos_->Clear();
    }
  }
  _impl_.id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SC_CLIENTCONNECT::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> SC_CLIENTCONNECT::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_SC_CLIENTCONNECT_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_CLIENTCONNECT, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.id_)}},
    // .CHARDATA charData = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.chardata_)}},
    // .POSITION startPos = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.startpos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .CHARDATA charData = 2;
    {PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.chardata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .POSITION startPos = 3;
    {PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.startpos_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::CHARDATA>()},
    {::_pbi::TcParser::GetTable<::POSITION>()},
  }}, {{
  }},
};

::uint8_t* SC_CLIENTCONNECT::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SC_CLIENTCONNECT)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .CHARDATA charData = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::chardata(this),
        _Internal::chardata(this).GetCachedSize(), target, stream);
  }

  // .POSITION startPos = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, _Internal::startpos(this),
        _Internal::startpos(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SC_CLIENTCONNECT)
  return target;
}

::size_t SC_CLIENTCONNECT::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SC_CLIENTCONNECT)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .CHARDATA charData = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.chardata_);
    }

    // .POSITION startPos = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.startpos_);
    }

  }
  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SC_CLIENTCONNECT::_class_data_ = {
    SC_CLIENTCONNECT::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SC_CLIENTCONNECT::GetClassData() const {
  return &_class_data_;
}

void SC_CLIENTCONNECT::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SC_CLIENTCONNECT*>(&to_msg);
  auto& from = static_cast<const SC_CLIENTCONNECT&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SC_CLIENTCONNECT)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_chardata()->::CHARDATA::MergeFrom(
          from._internal_chardata());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_startpos()->::POSITION::MergeFrom(
          from._internal_startpos());
    }
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_CLIENTCONNECT::CopyFrom(const SC_CLIENTCONNECT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SC_CLIENTCONNECT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SC_CLIENTCONNECT::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SC_CLIENTCONNECT::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SC_CLIENTCONNECT::InternalSwap(SC_CLIENTCONNECT* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.id_)
      + sizeof(SC_CLIENTCONNECT::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(SC_CLIENTCONNECT, _impl_.chardata_)>(
          reinterpret_cast<char*>(&_impl_.chardata_),
          reinterpret_cast<char*>(&other->_impl_.chardata_));
}

::google::protobuf::Metadata SC_CLIENTCONNECT::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[2]);
}
// ===================================================================

class SC_POS::_Internal {
 public:
  using HasBits = decltype(std::declval<SC_POS>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(SC_POS, _impl_._has_bits_);
  static const ::POSITION& pos(const SC_POS* msg);
  static void set_has_pos(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::POSITION& SC_POS::_Internal::pos(const SC_POS* msg) {
  return *msg->_impl_.pos_;
}
SC_POS::SC_POS(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SC_POS)
}
inline PROTOBUF_NDEBUG_INLINE SC_POS::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SC_POS::SC_POS(
    ::google::protobuf::Arena* arena,
    const SC_POS& from)
    : ::google::protobuf::Message(arena) {
  SC_POS* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pos_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::POSITION>(arena, *from._impl_.pos_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, move_time_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::move_time_));

  // @@protoc_insertion_point(copy_constructor:SC_POS)
}
inline PROTOBUF_NDEBUG_INLINE SC_POS::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_POS::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pos_),
           0,
           offsetof(Impl_, move_time_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::move_time_));
}
SC_POS::~SC_POS() {
  // @@protoc_insertion_point(destructor:SC_POS)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SC_POS::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.pos_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SC_POS::Clear() {
// @@protoc_insertion_point(message_clear_start:SC_POS)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.pos_ != nullptr);
    _impl_.pos_->Clear();
  }
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.move_time_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.move_time_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SC_POS::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> SC_POS::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_POS, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_SC_POS_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_POS, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.id_)}},
    // .POSITION pos = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.pos_)}},
    // int64 move_time = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_POS, _impl_.move_time_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.move_time_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .POSITION pos = 2;
    {PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.pos_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int64 move_time = 3;
    {PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.move_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }}, {{
    {::_pbi::TcParser::GetTable<::POSITION>()},
  }}, {{
  }},
};

::uint8_t* SC_POS::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SC_POS)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .POSITION pos = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::pos(this),
        _Internal::pos(this).GetCachedSize(), target, stream);
  }

  // int64 move_time = 3;
  if (this->_internal_move_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_move_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SC_POS)
  return target;
}

::size_t SC_POS::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SC_POS)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .POSITION pos = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pos_);
  }

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  // int64 move_time = 3;
  if (this->_internal_move_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_move_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SC_POS::_class_data_ = {
    SC_POS::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SC_POS::GetClassData() const {
  return &_class_data_;
}

void SC_POS::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SC_POS*>(&to_msg);
  auto& from = static_cast<const SC_POS&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SC_POS)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_pos()->::POSITION::MergeFrom(
        from._internal_pos());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_move_time() != 0) {
    _this->_internal_set_move_time(from._internal_move_time());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_POS::CopyFrom(const SC_POS& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SC_POS)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SC_POS::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SC_POS::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SC_POS::InternalSwap(SC_POS* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.move_time_)
      + sizeof(SC_POS::_impl_.move_time_)
      - PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::google::protobuf::Metadata SC_POS::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[3]);
}
// ===================================================================

class SC_REMOVE_OBJECT::_Internal {
 public:
};

SC_REMOVE_OBJECT::SC_REMOVE_OBJECT(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SC_REMOVE_OBJECT)
}
SC_REMOVE_OBJECT::SC_REMOVE_OBJECT(
    ::google::protobuf::Arena* arena, const SC_REMOVE_OBJECT& from)
    : SC_REMOVE_OBJECT(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SC_REMOVE_OBJECT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_REMOVE_OBJECT::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
SC_REMOVE_OBJECT::~SC_REMOVE_OBJECT() {
  // @@protoc_insertion_point(destructor:SC_REMOVE_OBJECT)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SC_REMOVE_OBJECT::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SC_REMOVE_OBJECT::Clear() {
// @@protoc_insertion_point(message_clear_start:SC_REMOVE_OBJECT)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SC_REMOVE_OBJECT::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SC_REMOVE_OBJECT::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SC_REMOVE_OBJECT_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_REMOVE_OBJECT, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SC_REMOVE_OBJECT, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(SC_REMOVE_OBJECT, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* SC_REMOVE_OBJECT::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SC_REMOVE_OBJECT)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SC_REMOVE_OBJECT)
  return target;
}

::size_t SC_REMOVE_OBJECT::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SC_REMOVE_OBJECT)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SC_REMOVE_OBJECT::_class_data_ = {
    SC_REMOVE_OBJECT::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SC_REMOVE_OBJECT::GetClassData() const {
  return &_class_data_;
}

void SC_REMOVE_OBJECT::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SC_REMOVE_OBJECT*>(&to_msg);
  auto& from = static_cast<const SC_REMOVE_OBJECT&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SC_REMOVE_OBJECT)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_REMOVE_OBJECT::CopyFrom(const SC_REMOVE_OBJECT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SC_REMOVE_OBJECT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SC_REMOVE_OBJECT::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SC_REMOVE_OBJECT::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SC_REMOVE_OBJECT::InternalSwap(SC_REMOVE_OBJECT* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata SC_REMOVE_OBJECT::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[4]);
}
// ===================================================================

class CS_LOGIN::_Internal {
 public:
};

CS_LOGIN::CS_LOGIN(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CS_LOGIN)
}
inline PROTOBUF_NDEBUG_INLINE CS_LOGIN::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : user_name_(arena, from.user_name_),
        _cached_size_{0} {}

CS_LOGIN::CS_LOGIN(
    ::google::protobuf::Arena* arena,
    const CS_LOGIN& from)
    : ::google::protobuf::Message(arena) {
  CS_LOGIN* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.time_test_ = from._impl_.time_test_;

  // @@protoc_insertion_point(copy_constructor:CS_LOGIN)
}
inline PROTOBUF_NDEBUG_INLINE CS_LOGIN::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_name_(arena),
        _cached_size_{0} {}

inline void CS_LOGIN::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.time_test_ = {};
}
CS_LOGIN::~CS_LOGIN() {
  // @@protoc_insertion_point(destructor:CS_LOGIN)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CS_LOGIN::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.user_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CS_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:CS_LOGIN)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_name_.ClearToEmpty();
  _impl_.time_test_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CS_LOGIN::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> CS_LOGIN::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CS_LOGIN_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 time_test = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CS_LOGIN, _impl_.time_test_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.time_test_)}},
    // bytes user_name = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.user_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes user_name = 1;
    {PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.user_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int64 time_test = 2;
    {PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.time_test_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CS_LOGIN::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CS_LOGIN)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes user_name = 1;
  if (!this->_internal_user_name().empty()) {
    const std::string& _s = this->_internal_user_name();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // int64 time_test = 2;
  if (this->_internal_time_test() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_time_test(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CS_LOGIN)
  return target;
}

::size_t CS_LOGIN::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CS_LOGIN)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes user_name = 1;
  if (!this->_internal_user_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_user_name());
  }

  // int64 time_test = 2;
  if (this->_internal_time_test() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_time_test());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CS_LOGIN::_class_data_ = {
    CS_LOGIN::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CS_LOGIN::GetClassData() const {
  return &_class_data_;
}

void CS_LOGIN::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CS_LOGIN*>(&to_msg);
  auto& from = static_cast<const CS_LOGIN&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CS_LOGIN)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_name().empty()) {
    _this->_internal_set_user_name(from._internal_user_name());
  }
  if (from._internal_time_test() != 0) {
    _this->_internal_set_time_test(from._internal_time_test());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_LOGIN::CopyFrom(const CS_LOGIN& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CS_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CS_LOGIN::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CS_LOGIN::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CS_LOGIN::InternalSwap(CS_LOGIN* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_name_, &other->_impl_.user_name_, arena);
        swap(_impl_.time_test_, other->_impl_.time_test_);
}

::google::protobuf::Metadata CS_LOGIN::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[5]);
}
// ===================================================================

class CS_MOVE::_Internal {
 public:
  using HasBits = decltype(std::declval<CS_MOVE>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_._has_bits_);
  static const ::POSITION& pos(const CS_MOVE* msg);
  static void set_has_pos(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::POSITION& CS_MOVE::_Internal::pos(const CS_MOVE* msg) {
  return *msg->_impl_.pos_;
}
CS_MOVE::CS_MOVE(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CS_MOVE)
}
inline PROTOBUF_NDEBUG_INLINE CS_MOVE::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CS_MOVE::CS_MOVE(
    ::google::protobuf::Arena* arena,
    const CS_MOVE& from)
    : ::google::protobuf::Message(arena) {
  CS_MOVE* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pos_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::POSITION>(arena, *from._impl_.pos_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, move_time_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::move_time_));

  // @@protoc_insertion_point(copy_constructor:CS_MOVE)
}
inline PROTOBUF_NDEBUG_INLINE CS_MOVE::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CS_MOVE::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pos_),
           0,
           offsetof(Impl_, move_time_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::move_time_));
}
CS_MOVE::~CS_MOVE() {
  // @@protoc_insertion_point(destructor:CS_MOVE)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CS_MOVE::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.pos_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CS_MOVE::Clear() {
// @@protoc_insertion_point(message_clear_start:CS_MOVE)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.pos_ != nullptr);
    _impl_.pos_->Clear();
  }
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.move_time_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.move_time_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CS_MOVE::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> CS_MOVE::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CS_MOVE_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CS_MOVE, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.id_)}},
    // .POSITION pos = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.pos_)}},
    // int64 move_time = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CS_MOVE, _impl_.move_time_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.move_time_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .POSITION pos = 2;
    {PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.pos_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int64 move_time = 3;
    {PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.move_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }}, {{
    {::_pbi::TcParser::GetTable<::POSITION>()},
  }}, {{
  }},
};

::uint8_t* CS_MOVE::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CS_MOVE)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .POSITION pos = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::pos(this),
        _Internal::pos(this).GetCachedSize(), target, stream);
  }

  // int64 move_time = 3;
  if (this->_internal_move_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_move_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CS_MOVE)
  return target;
}

::size_t CS_MOVE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CS_MOVE)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .POSITION pos = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pos_);
  }

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  // int64 move_time = 3;
  if (this->_internal_move_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_move_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CS_MOVE::_class_data_ = {
    CS_MOVE::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CS_MOVE::GetClassData() const {
  return &_class_data_;
}

void CS_MOVE::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CS_MOVE*>(&to_msg);
  auto& from = static_cast<const CS_MOVE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CS_MOVE)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_pos()->::POSITION::MergeFrom(
        from._internal_pos());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_move_time() != 0) {
    _this->_internal_set_move_time(from._internal_move_time());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_MOVE::CopyFrom(const CS_MOVE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CS_MOVE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CS_MOVE::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CS_MOVE::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CS_MOVE::InternalSwap(CS_MOVE* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.move_time_)
      + sizeof(CS_MOVE::_impl_.move_time_)
      - PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::google::protobuf::Metadata CS_MOVE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[6]);
}
// ===================================================================

class CS_LOGOUT::_Internal {
 public:
};

CS_LOGOUT::CS_LOGOUT(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CS_LOGOUT)
}
CS_LOGOUT::CS_LOGOUT(
    ::google::protobuf::Arena* arena, const CS_LOGOUT& from)
    : CS_LOGOUT(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CS_LOGOUT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CS_LOGOUT::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
CS_LOGOUT::~CS_LOGOUT() {
  // @@protoc_insertion_point(destructor:CS_LOGOUT)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CS_LOGOUT::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CS_LOGOUT::Clear() {
// @@protoc_insertion_point(message_clear_start:CS_LOGOUT)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CS_LOGOUT::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CS_LOGOUT::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CS_LOGOUT_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CS_LOGOUT, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CS_LOGOUT, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(CS_LOGOUT, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CS_LOGOUT::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CS_LOGOUT)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CS_LOGOUT)
  return target;
}

::size_t CS_LOGOUT::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CS_LOGOUT)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CS_LOGOUT::_class_data_ = {
    CS_LOGOUT::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CS_LOGOUT::GetClassData() const {
  return &_class_data_;
}

void CS_LOGOUT::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CS_LOGOUT*>(&to_msg);
  auto& from = static_cast<const CS_LOGOUT&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CS_LOGOUT)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_LOGOUT::CopyFrom(const CS_LOGOUT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CS_LOGOUT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CS_LOGOUT::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CS_LOGOUT::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CS_LOGOUT::InternalSwap(CS_LOGOUT* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata CS_LOGOUT::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[7]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
