// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tag.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_Tag_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Tag_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Tag_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Tag_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Tag_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum TAG_CS : int {
  TAG_CS_LOGIN = 0,
  TAG_CS_MOVE = 1,
  TAG_CS_ATTACK = 2,
  TAG_CS_LOGOUT = 3,
  TAG_CS_PLAYERSTATE = 4,
  TAG_CS_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TAG_CS_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool TAG_CS_IsValid(int value);
extern const uint32_t TAG_CS_internal_data_[];
constexpr TAG_CS TAG_CS_MIN = static_cast<TAG_CS>(0);
constexpr TAG_CS TAG_CS_MAX = static_cast<TAG_CS>(4);
constexpr int TAG_CS_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
TAG_CS_descriptor();
template <typename T>
const std::string& TAG_CS_Name(T value) {
  static_assert(std::is_same<T, TAG_CS>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TAG_CS_Name().");
  return TAG_CS_Name(static_cast<TAG_CS>(value));
}
template <>
inline const std::string& TAG_CS_Name(TAG_CS value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TAG_CS_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool TAG_CS_Parse(absl::string_view name, TAG_CS* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TAG_CS>(
      TAG_CS_descriptor(), name, value);
}
enum TAG_SC : int {
  TAG_SC_CONNECTSUCCESS = 0,
  TAG_SC_OTHERCLIENTLOGIN = 1,
  TAG_SC_MOVEFAILED = 2,
  TAG_SC_OTHERMOVE = 3,
  TAG_SC_VIEWINRANGE = 4,
  TAG_SC_PLAYERSTATE = 5,
  TAG_SC_MOVESTATE = 6,
  TAG_SC_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TAG_SC_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool TAG_SC_IsValid(int value);
extern const uint32_t TAG_SC_internal_data_[];
constexpr TAG_SC TAG_SC_MIN = static_cast<TAG_SC>(0);
constexpr TAG_SC TAG_SC_MAX = static_cast<TAG_SC>(6);
constexpr int TAG_SC_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor*
TAG_SC_descriptor();
template <typename T>
const std::string& TAG_SC_Name(T value) {
  static_assert(std::is_same<T, TAG_SC>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TAG_SC_Name().");
  return TAG_SC_Name(static_cast<TAG_SC>(value));
}
template <>
inline const std::string& TAG_SC_Name(TAG_SC value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TAG_SC_descriptor,
                                                 0, 6>(
      static_cast<int>(value));
}
inline bool TAG_SC_Parse(absl::string_view name, TAG_SC* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TAG_SC>(
      TAG_SC_descriptor(), name, value);
}
enum TAG_CHAR : int {
  TAG_MAINPLAYER = 0,
  TAG_OTHERPLAYER = 1,
  TAG_MUMMY = 2,
  TAG_CHAR_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TAG_CHAR_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool TAG_CHAR_IsValid(int value);
extern const uint32_t TAG_CHAR_internal_data_[];
constexpr TAG_CHAR TAG_CHAR_MIN = static_cast<TAG_CHAR>(0);
constexpr TAG_CHAR TAG_CHAR_MAX = static_cast<TAG_CHAR>(2);
constexpr int TAG_CHAR_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
TAG_CHAR_descriptor();
template <typename T>
const std::string& TAG_CHAR_Name(T value) {
  static_assert(std::is_same<T, TAG_CHAR>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TAG_CHAR_Name().");
  return TAG_CHAR_Name(static_cast<TAG_CHAR>(value));
}
template <>
inline const std::string& TAG_CHAR_Name(TAG_CHAR value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TAG_CHAR_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool TAG_CHAR_Parse(absl::string_view name, TAG_CHAR* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TAG_CHAR>(
      TAG_CHAR_descriptor(), name, value);
}
enum TAG_PLAYERTYPE : int {
  TAG_WARRIOR = 0,
  TAG_ARCHOR = 1,
  TAG_MAGICAIN = 2,
  TAG_PLAYERTYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TAG_PLAYERTYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool TAG_PLAYERTYPE_IsValid(int value);
extern const uint32_t TAG_PLAYERTYPE_internal_data_[];
constexpr TAG_PLAYERTYPE TAG_PLAYERTYPE_MIN = static_cast<TAG_PLAYERTYPE>(0);
constexpr TAG_PLAYERTYPE TAG_PLAYERTYPE_MAX = static_cast<TAG_PLAYERTYPE>(2);
constexpr int TAG_PLAYERTYPE_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
TAG_PLAYERTYPE_descriptor();
template <typename T>
const std::string& TAG_PLAYERTYPE_Name(T value) {
  static_assert(std::is_same<T, TAG_PLAYERTYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TAG_PLAYERTYPE_Name().");
  return TAG_PLAYERTYPE_Name(static_cast<TAG_PLAYERTYPE>(value));
}
template <>
inline const std::string& TAG_PLAYERTYPE_Name(TAG_PLAYERTYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TAG_PLAYERTYPE_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool TAG_PLAYERTYPE_Parse(absl::string_view name, TAG_PLAYERTYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TAG_PLAYERTYPE>(
      TAG_PLAYERTYPE_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::TAG_CS> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::TAG_CS>() {
  return ::TAG_CS_descriptor();
}
template <>
struct is_proto_enum<::TAG_SC> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::TAG_SC>() {
  return ::TAG_SC_descriptor();
}
template <>
struct is_proto_enum<::TAG_CHAR> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::TAG_CHAR>() {
  return ::TAG_CHAR_descriptor();
}
template <>
struct is_proto_enum<::TAG_PLAYERTYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::TAG_PLAYERTYPE>() {
  return ::TAG_PLAYERTYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Tag_2eproto_2epb_2eh
