// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tag.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_Tag_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Tag_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Tag_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Tag_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Tag_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum TAG_CS : int {
  TAG_CS_LOGIN = 0,
  TAG_CS_MOVE = 1,
  TAG_CS_CHAT = 2,
  TAG_CS_LOGOUT = 3,
  TAG_CS_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TAG_CS_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool TAG_CS_IsValid(int value);
extern const uint32_t TAG_CS_internal_data_[];
constexpr TAG_CS TAG_CS_MIN = static_cast<TAG_CS>(0);
constexpr TAG_CS TAG_CS_MAX = static_cast<TAG_CS>(3);
constexpr int TAG_CS_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
TAG_CS_descriptor();
template <typename T>
const std::string& TAG_CS_Name(T value) {
  static_assert(std::is_same<T, TAG_CS>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TAG_CS_Name().");
  return TAG_CS_Name(static_cast<TAG_CS>(value));
}
template <>
inline const std::string& TAG_CS_Name(TAG_CS value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TAG_CS_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool TAG_CS_Parse(absl::string_view name, TAG_CS* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TAG_CS>(
      TAG_CS_descriptor(), name, value);
}
enum TAG_SERVER : int {
  TAG_SC_LOGIN = 0,
  TAG_SC_MOVE = 1,
  TAG_SC_CHAT = 2,
  TAG_SC_LOGOUT = 3,
  TAG_SERVER_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TAG_SERVER_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool TAG_SERVER_IsValid(int value);
extern const uint32_t TAG_SERVER_internal_data_[];
constexpr TAG_SERVER TAG_SERVER_MIN = static_cast<TAG_SERVER>(0);
constexpr TAG_SERVER TAG_SERVER_MAX = static_cast<TAG_SERVER>(3);
constexpr int TAG_SERVER_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
TAG_SERVER_descriptor();
template <typename T>
const std::string& TAG_SERVER_Name(T value) {
  static_assert(std::is_same<T, TAG_SERVER>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TAG_SERVER_Name().");
  return TAG_SERVER_Name(static_cast<TAG_SERVER>(value));
}
template <>
inline const std::string& TAG_SERVER_Name(TAG_SERVER value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TAG_SERVER_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool TAG_SERVER_Parse(absl::string_view name, TAG_SERVER* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TAG_SERVER>(
      TAG_SERVER_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::TAG_CS> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::TAG_CS>() {
  return ::TAG_CS_descriptor();
}
template <>
struct is_proto_enum<::TAG_SERVER> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::TAG_SERVER>() {
  return ::TAG_SERVER_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Tag_2eproto_2epb_2eh
